In [13]:
file_path = "/Users/yang/Desktop/data_check.txt"

with open(file_path, "r") as f:
    data = f.read()

In [15]:
blocks = data.split("-----------------------------------")

In [17]:
import re
import pandas as pd

rows = []

for block in blocks:
    
    recipe_index = re.search(r"Recipe Index: (\d+)", block)
    recipe_name = re.search(r"Recipe Name: (.+)", block)
    ingredient = re.search(r"Ingredient: (.+)", block)
    products_found = re.search(r"Products Found: (\d+)", block)

    rows.append({
        "recipe_index": recipe_index.group(1) if recipe_index else None,
        "recipe_name": recipe_name.group(1) if recipe_name else None,
        "ingredient": ingredient.group(1) if ingredient else None,
        "products_found": int(products_found.group(1)) if products_found else None
    })

df = pd.DataFrame(rows)

df.head()

,recipe_index,recipe_name,ingredient,products_found
0,None,None,None,NaN
1,14,Black-Eyed Pea Burritos,dried black-eyed peas,1.0
2,19,Pork & Shrimp Spring Roll With Peanut Sauce,fresh cilantro stems,0.0
3,19,Pork & Shrimp Spring Roll With Peanut Sauce,unsalted dry roasted peanuts,1.0
4,20,Strawberry-Rhubarb Pie,fresh rhubarb,1.0

In [19]:
df["ingredient_normalized"] = df["ingredient"]

In [21]:
ingredient_map_zero = {
    "fresh cilantro stems": "cilantro",
    "Quick & Easy Tahini Sauce": "tahini sauce",
    "sultana": "golden raisins",
    "black cardamom pods": "black cardamom",
    "red capsicum": "red bell pepper",
    "Jump up and Smack Your Mom Hot Sauce": "hot sauce"
}

df["ingredient_normalized"] = df["ingredient_normalized"].replace(ingredient_map_zero)

In [23]:
df[df["products_found"] == 0][["recipe_name","ingredient","ingredient_normalized"]]

,recipe_name,ingredient,ingredient_normalized
2,Pork & Shrimp Spring Roll With Peanut Sauce,fresh cilantro stems,cilantro
6,"Roast Cauliflower With Almond, Pomegranate See...",Quick & Easy Tahini Sauce,tahini sauce
8,Carrot Cake Slice,sultana,golden raisins
13,Braised Chicken with Onions and Tomatoes,black cardamom pods,black cardamom
16,Caramel Sultana Square,sultana,golden raisins
25,Drunken Noodles,red capsicum,red bell pepper
28,Spinach Capsicum and Feta Pizza,red capsicum,red bell pepper
34,Shadow's Barbecue Sauce,Jump up and Smack Your Mom Hot Sauce,hot sauce
44,Thai Fish Curry,fresh cilantro stems,cilantro

In [25]:
df.to_csv("/Users/yang/Desktop/clean_recipe_data.csv", index=False)

In [27]:
import pandas as pd

df = pd.read_csv("/Users/yang/Desktop/clean_recipe_data.csv")

df.head()

,recipe_index,recipe_name,ingredient,products_found,ingredient_normalized
0,NaN,NaN,NaN,NaN,NaN
1,14.0,Black-Eyed Pea Burritos,dried black-eyed peas,1.0,dried black-eyed peas
2,19.0,Pork & Shrimp Spring Roll With Peanut Sauce,fresh cilantro stems,0.0,cilantro
3,19.0,Pork & Shrimp Spring Roll With Peanut Sauce,unsalted dry roasted peanuts,1.0,unsalted dry roasted peanuts
4,20.0,Strawberry-Rhubarb Pie,fresh rhubarb,1.0,fresh rhubarb

In [29]:
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   recipe_index           48 non-null     float64
 1   recipe_name            48 non-null     object
 2   ingredient             46 non-null     object
 3   products_found         46 non-null     float64
 4   ingredient_normalized  46 non-null     object
dtypes: float64(2), object(3)
memory usage: 2.0+ KB

0

In [33]:
df["products_found"].value_counts()

products_found
1.0    37
0.0     9
Name: count, dtype: int64

In [35]:
df[df["ingredient"] != df["ingredient_normalized"]]

,recipe_index,recipe_name,ingredient,products_found,ingredient_normalized
0,NaN,NaN,NaN,NaN,NaN
2,19.0,Pork & Shrimp Spring Roll With Peanut Sauce,fresh cilantro stems,0.0,cilantro
6,27.0,"Roast Cauliflower With Almond, Pomegranate See...",Quick & Easy Tahini Sauce,0.0,tahini sauce
8,30.0,Carrot Cake Slice,sultana,0.0,golden raisins
13,58.0,Braised Chicken with Onions and Tomatoes,black cardamom pods,0.0,black cardamom
16,64.0,Caramel Sultana Square,sultana,0.0,golden raisins
25,107.0,Drunken Noodles,red capsicum,0.0,red bell pepper
28,113.0,Spinach Capsicum and Feta Pizza,red capsicum,0.0,red bell pepper
30,125.0,Tennessee Tea [mocktail],NaN,NaN,NaN
34,149.0,Shadow's Barbecue Sauce,Jump up and Smack Your Mom Hot Sauce,0.0,hot sauce
36,163.0,Tangy Potato Salad,NaN,NaN,NaN
44,223.0,Thai Fish Curry,fresh cilantro stems,0.0,cilantro

In [39]:
df[df["products_found"] == 0][
    ["recipe_index","recipe_name","ingredient","ingredient_normalized"]
]

,recipe_index,recipe_name,ingredient,ingredient_normalized
2,19.0,Pork & Shrimp Spring Roll With Peanut Sauce,fresh cilantro stems,cilantro
6,27.0,"Roast Cauliflower With Almond, Pomegranate See...",Quick & Easy Tahini Sauce,tahini sauce
8,30.0,Carrot Cake Slice,sultana,golden raisins
13,58.0,Braised Chicken with Onions and Tomatoes,black cardamom pods,black cardamom
16,64.0,Caramel Sultana Square,sultana,golden raisins
25,107.0,Drunken Noodles,red capsicum,red bell pepper
28,113.0,Spinach Capsicum and Feta Pizza,red capsicum,red bell pepper
34,149.0,Shadow's Barbecue Sauce,Jump up and Smack Your Mom Hot Sauce,hot sauce
44,223.0,Thai Fish Curry,fresh cilantro stems,cilantro

In [41]:
df.shape

(49, 5)